<?php

namespace Tests\Feature;

use Auth;
use Artisan;
use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class UserLoginTest extends TestCase
{
    use DatabaseTransactions;

    public function setUp(){
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');
    }

    /** @test */
    public function it_should_allow_login_by_email()
    {
        $user = factory(User::class)->create(['password' => bcrypt('admin123')]);
        $authed = Auth::attempt(['email' => $user->email, 'password' => 'admin123']);
        $this->assertTrue($authed, 'Auth by email failed');
    }

    /** @test */
    public function it_should_allow_login_by_user_name()
    {
        $user = factory(User::class)->create(['password' => bcrypt('admin123')]);
        $authed = Auth::attempt(['user_name' => $user->user_name, 'password' => 'admin123']);
        $this->assertTrue($authed, 'Auth by user name failed');
    }
}
