-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 15:31:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoipos_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoipos_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoipos_v2` DEFAULT CHARACTER SET utf8 ;
USE `hoipos_v2` ;

-- -----------------------------------------------------
-- Table `hoipos_v2`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `salutation` VARCHAR(32) NULL,
  `first_name` TEXT NULL,
  `last_name` TEXT NULL,
  `email` TEXT NULL,
  `phone_country_code` VARCHAR(32) NULL,
  `phone` TEXT NULL,
  `address` TEXT NULL,
  `gender` TINYINT NULL,
  `birthday` DATE NULL,
  `points` INT NULL,
  `barcode` VARCHAR(128) NULL,
  `language` VARCHAR(45) NULL,
  `brand` BIGINT NULL,
  `modified_timestamp` TIMESTAMP NULL,
  `created_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoipos_v2`.`customer_authentication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`customer_authentication` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fb_uid` TEXT NULL,
  `password_hash` TEXT NULL,
  `modified_timestamp` TIMESTAMP NULL,
  `created_timestamp` TIMESTAMP NULL,
  `last_login_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoipos_v2`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`reservation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `outlet_id` BIGINT NULL,
  `customer_id` BIGINT NULL,
  `salutation` VARCHAR(32) NULL,
  `first_name` TEXT NULL,
  `last_name` TEXT NULL,
  `email` TEXT NULL,
  `phone_country_code` VARCHAR(32) NULL,
  `phone` TEXT NULL,
  `customer_remarks` TEXT NULL,
  `adult_pax` INT NULL,
  `children_pax` INT NULL,
  `reservation_timestamp` TIMESTAMP NULL,
  `table_layout_id` BIGINT NULL,
  `table_layout_name` VARCHAR(16) NULL,
  `table_name` VARCHAR(16) NULL,
  `staff_remarks` TEXT NULL,
  `status` INT NULL COMMENT '100=reserved,200=reminder sent,300=confirmed,400=arrived,-100=user cancelled,-200=staff cancelled,-300=no show',
  `send_confirmation_by_timestamp` TIMESTAMP NULL,
  `send_sms_confirmation` TINYINT NULL,
  `send_email_confirmation` TINYINT NULL,
  `session_name` TEXT NULL,
  `reservation_code` VARCHAR(16) NULL,
  `staff_read_state` TINYINT NULL,
  `created_timestamp` TIMESTAMP NULL,
  `modified_timestamp` TIMESTAMP NULL,
  `payment_id` TEXT NULL,
  `payment_timestamp` TIMESTAMP NULL,
  `payment_amount` DECIMAL(32,2) NULL,
  `payment_required` TINYINT NULL,
  `is_outdoor` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoipos_v2`.`outlet_reservation_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`outlet_reservation_setting` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `outlet_id` BIGINT NULL,
  `setting_group` INT NULL COMMENT '1=buffers,2=notifications,3=others',
  `setting_key` TEXT NULL,
  `setting_value` TEXT NULL,
  `setting_type` TINYINT NULL,
  `created_timestamp` TIMESTAMP NULL,
  `modified_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoipos_v2`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `outlet_id` BIGINT NULL,
  `session_name` TEXT NULL,
  `on_mondays` TINYINT NULL,
  `on_tuesdays` TINYINT NULL,
  `on_wednesdays` TINYINT NULL,
  `on_thursdays` TINYINT NULL,
  `on_fridays` TINYINT NULL,
  `on_saturdays` TINYINT NULL,
  `on_sundays` TINYINT NULL,
  `modified_timestamp` TIMESTAMP NULL,
  `created_timestamp` TIMESTAMP NULL,
  `one_off` TINYINT NULL,
  `one_off_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoipos_v2`.`timing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`timing` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `session_id` BIGINT NULL,
  `timing_name` TEXT NULL,
  `first_arrival_time` TIME NULL,
  `last_arrival_time` TIME NULL,
  `interval_minutes` INT NULL,
  `capacity_1` INT NULL,
  `capacity_2` INT NULL,
  `capacity_3_4` INT NULL,
  `capacity_5_6` INT NULL,
  `capacity_7_x` INT NULL,
  `max_pax` INT NULL,
  `children_allowed` TINYINT NULL,
  `min_pax_for_booking_deposit` INT NULL,
  `booking_deposit_type` TINYINT NULL COMMENT '1=per head,2=lump sum',
  `booking_deposit_amount` DECIMAL(32,2) NULL,
  `disabled` TINYINT NULL,
  `created_timestamp` TIMESTAMP NULL,
  `modified_timestamp` TIMESTAMP NULL,
  `is_outdoor` TINYINT NULL COMMENT 'to indicate alternative slots for outdoor',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoipos_v2`.`outlet_reservation_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`outlet_reservation_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `outlet_ids` TEXT NULL,
  `user_name` TEXT NULL,
  `password_hash` TEXT NULL,
  `email` TEXT NULL,
  `display_name` TEXT NULL,
  `permission_level` INT NULL COMMENT '0= full administrator, 500 = see and manage reservations only',
  `secret_token` VARCHAR(200) NULL,
  `secret_expiry` TIMESTAMP NULL,
  `pending_password_reset` TINYINT NULL,
  `created_timestamp` TIMESTAMP NULL,
  `modified_timestamp` TIMESTAMP NULL,
  `last_login_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoipos_v2`.`outlet_reservation_user_reset_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoipos_v2`.`outlet_reservation_user_reset_password` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL,
  `reset_token` VARCHAR(64) NULL,
  `created_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
