<?php
namespace App\Libraries;

class HoiAjaxCall {
    // AJAX ACTION
    const AJAX_ADD_WEEKLY_SESSIONS    = 'AJAX_ADD_WEEKLY_SESSIONS';
    const AJAX_UPDATE_WEEKLY_SESSIONS = 'AJAX_UPDATE_WEEKLY_SESSIONS';
    const AJAX_DELETE_WEEKLY_SESSIONS = 'AJAX_DELETE_WEEKLY_SESSIONS';
    const AJAX_UPDATE_SESSIONS        = 'AJAX_UPDATE_SESSIONS';
    const AJAX_UPDATE_BUFFER          = 'AJAX_UPDATE_BUFFER';
    const AJAX_UPDATE_NOTIFICATION    = 'AJAX_UPDATE_NOTIFICATION';
    const AJAX_UPDATE_SETTINGS        = 'AJAX_UPDATE_SETTINGS';
    const AJAX_UPDATE_DEPOSIT         = 'AJAX_UPDATE_DEPOSIT';
    const AJAX_UPDATE_RESERVATIONS    = 'AJAX_UPDATE_RESERVATIONS';
    const AJAX_REFETCHING_DATA        = 'AJAX_REFETCHING_DATA';


//AJAX MSG
    const AJAX_UNKNOWN_CASE                   = 'AJAX_UNKNOWN_CASE';
    const AJAX_UPDATE_WEEKLY_SESSIONS_SUCCESS = 'AJAX_UPDATE_WEEKLY_SESSIONS_SUCCESS';
    const AJAX_UPDATE_WEEKLY_SESSIONS_ERROR   = 'AJAX_UPDATE_WEEKLY_SESSIONS_ERROR';
    const AJAX_UPDATE_SESSIONS_SUCCESS        = 'AJAX_UPDATE_SESSIONS_SUCCESS';
    const AJAX_UPDATE_SCOPE_OUTLET_ID_SUCCESS = 'AJAX_UPDATE_SCOPE_OUTLET_ID_SUCCESS';

    const AJAX_SUCCESS  = 'AJAX_SUCCESS';
    const AJAX_ERROR    = 'AJAX_ERROR';

    const AJAX_VALIDATE_FAIL = 'AJAX_VALIDATE_FAIL';

    const AJAX_UPDATE_SCOPE_OUTLET_ID_ERROR = 'AJAX_UPDATE_SCOPE_OUTLET_ID_ERROR';
    const AJAX_REFETCHING_DATA_SUCCESS = 'AJAX_REFETCHING_DATA_SUCCESS';

    const AJAX_SEARCH_AVAILABLE_TIME  = 'AJAX_SEARCH_AVAILABLE_TIME';
    const AJAX_SUBMIT_BOOKING         = 'AJAX_SUBMIT_BOOKING';
    
    const AJAX_BOOKING_CONDITION_VALIDATE_FAIL = 'AJAX_BOOKING_CONDITION_VALIDATE_FAIL';

    const AJAX_AVAILABLE_TIME_FOUND = 'AJAX_AVAILABLE_TIME_FOUND';
    const AJAX_RESERVATION_VALIDATE_FAIL = 'AJAX_RESERVATION_VALIDATE_FAIL';
    const AJAX_RESERVATION_NO_LONGER_AVAILABLE = 'AJAX_RESERVATION_NO_LONGER_AVAILABLE';
    const AJAX_RESERVATION_REQUIRED_DEPOSIT = 'AJAX_RESERVATION_REQUIRED_DEPOSIT';
    const AJAX_RESERVATION_SUCCESS_CREATE = 'AJAX_RESERVATION_SUCCESS_CREATE';

}